#!/bin/bash

DIR=$(pwd)

#INSTALL DEBIAN PACKAGES
sudo apt install -y python3 python3-dev python3-pip
sudo apt-get install -y libatlas-base-dev libjasper-dev libqtgui4 libqt4-test python-smbus i2c-tools

#INSTALL PYTHON PACKAGES
sudo pip3 install "numpy==1.16.2" "six==1.12.0" "Cython==0.29.14" "Pillow==2.2.2" 
sudo pip3 install "evdev==1.1.2" "PySimpleGui==4.4.1" "PySimpleGUIQt==0.28.0" "opencv-python==3.4.3.18" "qrcode==6.1"
sudo pip3 install "adafruit-circuitpython-servokit==1.1.0"

if [ -f $DIR/local_variables ]; then 
	echo "Already setup"
	exit
fi
echo "REPO_PATH=$DIR" > $DIR/local_variables
echo "cd $DIR && ./jpo-startup &" >> $HOME/.profile 	
